name: "CI/CD"
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox tox-gh-actions
      - run: tox
